"""primeira

Revision ID: 1833bec19eaa
Revises: 
Create Date: 2024-11-20 13:12:33.550590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1833bec19eaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('clube',
    sa.Column('id_clube', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], ),
    sa.PrimaryKeyConstraint('id_clube')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clube')
    op.drop_table('alunos')
    # ### end Alembic commands ###
